# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492b292e60b93105ec95b90dc81564b5aea1d3db3690e8a9e02da1494222127099619d61b175d83cc764a383ba87c6315f0299ed0d6c755644a7c3485dfaea77

test:
  secret_key_base: d97b0452bfb15925910790232ae14728496137f25433458830a34f84cff98572071f87b9cf09fb603f48dd5b859a88341cb70ec627e4f022b60fa7f68b5e8049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
